# Generated by Django 5.2.4 on 2025-07-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('resolution', models.CharField(blank=True, max_length=30, null=True)),
                ('lens', models.CharField(blank=True, max_length=50, null=True)),
                ('night_vision', models.BooleanField(default=False)),
                ('connectivity', models.CharField(blank=True, max_length=50, null=True)),
                ('power', models.CharField(blank=True, max_length=30, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, default='default/cam.png', null=True, upload_to='cameras/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
