# Generated by Django 5.2.4 on 2025-07-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conditioners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('cooling_capacity', models.CharField(blank=True, max_length=20, null=True)),
                ('power_consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('inverter', models.BooleanField(default=False)),
                ('room_size', models.CharField(blank=True, max_length=50, null=True)),
                ('noise_level', models.CharField(blank=True, max_length=20, null=True)),
                ('functions', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, default='default/ac.png', null=True, upload_to='conditioners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
